version: '3.8'

services:
  spotter-db:
    image: postgis/postgis:13-3.1
    volumes:
      - spotter-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5434:5432"
  spotter-route:
    build:
      context: .
    image: spotter-route
    env_file:
      - .env
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - spotter-db
  nginx:
    image: nginx:latest
    volumes:
      - .nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    ports:
      - "8080:80"
    depends_on:
      - spotter-route
volumes:
  spotter-data:
  static: