# Generated by Django 3.2.23 on 2024-10-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_route', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelstationmodel',
            old_name='price',
            new_name='retail_price',
        ),
        migrations.RenameField(
            model_name='fuelstationmodel',
            old_name='name',
            new_name='truckstop_name',
        ),
        migrations.AddField(
            model_name='fuelstationmodel',
            name='rack_id',
            field=models.IntegerField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelstationmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
